### ISSUE TITLE
App crashes when the API key is empty

### ISSUE THREAD

**Issue by RvdK** [MatthijsKok/TI2806-Contextproject#108]
The app should not shut down when the api key is empty it should give an error

**Comment by joskuijpers** [comment]
What is the exception thrown?

**Comment by joskuijpers** [comment]
The issue is that the test fails when the API key in the test is empty, because the session does not create.
Workaround is to put the api key in the test.

Will look into a solution.

**Comment by joskuijpers** [comment]
Okay so the issue with the test is not easily solvable. The api key could be loaded from the environment.xml but only if the test is an Activity: otherwise there is no getResources().

**Comment by RvdK** [comment]
This no longer happens so i am closing the bug
