### ISSUE TITLE
Write draft of Architecture Design

### ISSUE THREAD

**Issue by RvdK** [MatthijsKok/TI2806-Contextproject#12]
Write a document containing of

**Introduction**

 - Design goals

**Software architecture views**

- Subsystem decomposition (sub-systems and dependencies between them)
- Hardware/software mapping (mapping of sub-systems to processes and computers, communication between computers),
- Persistent data management (file/ database, database design)
- Concurrency (processes, shared resources, communication between processes, deadlocks prevention)

**Glossary**

consisting of no more then 10 pages
 The initial version can contain sketches/ideas of the architecture design;

**Comment by RvdK** [comment]
https://www.sharelatex.com/project/5906f169e0b90d35795a8fa0

**Comment by joskuijpers** [comment]
Tasks
- Introduction #24 
- Subsystem decomposition #18
- Hardware/software mapping #19
- Persistent data management #20
- Concurrency #21
- Glossary #23

**Comment by joskuijpers** [comment]
I will work on this.

For this we need to figure out what dependencies we need for the app, how we store data persistently in the app and how the threads in Android works.

Regarding threads: it should not be difficult to run longer running tasks in a background thread. All graphics must be on the main thread.

I will try to figure out what classes we need and what we can do separately (subsystems).

I am already thinking about the banking API usage / implementation, blockchain API (with mock and simple storage), a challenge system and a persistent secure storage (for the priv+pub key and list of IBANs). The GUI is a single 'subsystem'.
I also think we might write an HTTP wrapper if the http lib we will use does not have testing support builtin (It might)
