### ISSUE TITLE
Non-reproducable lambda exception

### ISSUE THREAD

**Issue by Ishadijcks** [MatthijsKok/TI2806-Contextproject#123]
When opening the recentTransactions screen, the app sometimes crashes on the following call:

                return CompletableFuture
                .supplyAsync(this::loadOrCreateClientKeys)
                .thenComposeAsync(session::doInstallation)
                .thenComposeAsync(session::doDeviceRegistration)
                .thenComposeAsync(session::doSessionStart)

![image](https://cloud.githubusercontent.com/assets/9715314/26299399/02897de4-3edb-11e7-940b-9539113dc7ba.png)

It does not happen always, and it does not happen on everyone's machine.

**Comment by joskuijpers** [comment]
Is it fixed after a rebuild?

**Comment by joskuijpers** [comment]
Not reproducable.
