### ISSUE TITLE
Make IBAN serializable

### ISSUE THREAD

**Issue by clenrock** [MatthijsKok/TI2806-Contextproject#154]
- Parent issues: -
- Relevant issues: -
- Estimated effort: -1 hour

* * *

## User story

As a developer I want IBAN to be serializable so that users can send this through Bluetooth.

## What

This issue demands that IBAN will extend Serializable.

## Why

This issue is needed for the project because this makes the NervousFish team able to send the contact with IBAN through Bluetooth, instead of writing this manually every time a user is added.

## Definition of done

This task can be considered done when:
- [x] The IBAN class is serializable

## Notes

None

**Comment by joskuijpers** [comment]
Had already looked into it, but Android documentation suggested it might be better to use JsonReader and JsonWriter instead. 

This article gives more info:
http://www.javapractices.com/topic/TopicAction.do?Id=45

I'll implement it though. I assume you are using Serialize to store the blockchain?
