### ISSUE TITLE
Final polishing and testing

### ISSUE THREAD

**Issue by RvdK** [MatthijsKok/TI2806-Contextproject#162]
- Parent issues: -
- Relevant issues: -
- Estimated effort: 8h 

* * *

## User story
The appliction should be in its best possible state so we need to do some small final tweaks
## What
Some gui parts are not completely clear and the persistent storage is not yet properly implemented.

## Why
the application should be as nice as possible for the final delivery
## How
implement the created blockchain and use the user feedback from the human computer interaction study.
## Definition of done
- The blockchain must work with the validator
- main grievences from the hci study should be adressed

## Notes
None

**Comment by Ishadijcks** [comment]
Done
