### ISSUE TITLE
Write product vision timeframe and budget paragraph

### ISSUE THREAD

**Issue by RvdK** [MatthijsKok/TI2806-Contextproject#27]
What is the target timeframe and budget to develop and launch the product?

**Comment by Ishadijcks** [comment]
"There  is  no  real  budget  to  create  this  app  we  do  however  have  resources."
We konden toch geld krijgen van Johan als we moeten betalen voor die API/geld overmaken?

Application is een keer met en zonder hoofdletter.
Hardware met een hoofdletter?

Verder prima :)

**Comment by RvdK** [comment]
zal dat eerste er nog even bijzetten maar vond het niet heel belangrijk zeker niet als je naar de verhoudingen gaat kijken
