### ISSUE TITLE
Write a product planning: User stories ...

### ISSUE THREAD

**Issue by eriksennema** [MatthijsKok/TI2806-Contextproject#30]
The first version of the product backlog with estimates and prioritized user stories

**Comment by eriksennema** [comment]
- [ ] of features
- [x] of defects
- [x] of technical improvements
- [ ] of know-how acquisition

**Comment by Ishadijcks** [comment]
of defects and of technical improvements are empty in this first version of our Product Planning, as we haven't started developing yet.
