### ISSUE TITLE
API key Research

### ISSUE THREAD

**Issue by RvdK** [MatthijsKok/TI2806-Contextproject#85]
Find out if 1 API key can be used for multiple IP addresses. As we cannot estimate the implementation there is no way of telling if it can be implemented immediately

**Comment by joskuijpers** [comment]
So it seems that API keys get bound to an IP and it can't be changed, according to Bunq support.

To 'solve' this issue, I created a simple proxy server that proxies everything to the bunq sandbox: this means all calls will have the same IP address.
Note that there is NO SSL connection from the proxy to the client. And that this is against the terms of service of Bunq and MUST NOT be used outside the sandbox.
